"""initial models

Revision ID: 927533a0a133
Revises: 
Create Date: 2026-06-18 01:51:22.394046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927533a0a133'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('vault_salt', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_salt')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único del evento'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Usuario asociado al evento (nullable para eventos de sistema)'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Tipo de evento: LOGIN, PING_SENT, PING_ACKNOWLEDGED, ASSET_ACCESSED, SWITCH_TRIGGERED'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Descripción adicional del evento'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Dirección IP desde la cual se originó el evento'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora del evento'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('switch_configurations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único de la configuración'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Referencia única al usuario propietario'),
    sa.Column('ping_interval_days', sa.Integer(), nullable=False, comment='Número de días entre intentos de contacto automático'),
    sa.Column('trigger_after_days', sa.Integer(), nullable=False, comment='Número de días de inactividad para ejecutar el protocolo de sucesión'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de la última actividad confirmada del usuario'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado del switch: ACTIVE, WARNING, TRIGGERED'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la configuración'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_switch_configurations_id'), 'switch_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_switch_configurations_user_id'), 'switch_configurations', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_switch_configurations_user_id'), table_name='switch_configurations')
    op.drop_index(op.f('ix_switch_configurations_id'), table_name='switch_configurations')
    op.drop_table('switch_configurations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
